<?php
	// Deal or no Deal
	// Byteland is a country which consists of n square-shaped plots of land arranged linearly.
	// Each plot has a different cost, measured in gold coins.
	// Mr.Roy, a property dealer in byteland was contacted by a big firm ‘Decima Technologies’ who are looking to buy a single large chunk of land for their upcoming project, subject to the following rules :
	// They will only pay a fixed cost of c gold coins per plot.
	// Mr. Roy can sell as many plots as he wants (including zero), but the plots should be consecutive ,i.e, only a single chunk of land without any gap is allowed.
	// You have to help Mr.Roy in selecting the plots so that his profit is maximized.
	// Given the cost of each plot of land, and the value of c, you have to print the maximum profit that can be generated by selling the plots.
	
	// Input Format
	// The first line of input is an integer t which is the number of test cases. t test cases follow each of which contains two lines of input:
	// The first line contains n and c (space-separated integers)
	// The second line contains n space-separated integers denoting price of each plot.
	
	// Output Format
	// For each test case, output, on a different line, a single integer T which is the maximum profit that can be made. If no profit can be 
	// made output 0.
	
	// Sample Input
	// 9
	// 7 4
	// 9 2 5 7 2 5 9
	// 5 9
	// 2 2 1 4 9
	// 2 5
	// 5 4
	// 9 9
	// 2 2 1 8 7 4 7 2 6
	// 6 8
	// 1 2 5 4 2 4
	// 3 2
	// 5 8 9
	// 4 4
	// 1 4 8 1
	// 9 1
	// 3 3 1 2 9 9 9 6 1
	// 8 4
	// 9 2 4 1 4 3 8 2
	
	// Sample Output
	// 2
	// 27
	// 1
	// 42
	// 30
	// 0
	// 3
	// 0
	// 6

	fscanf(STDIN, "%d", $t);
	for($loop = 0; $loop < $t; $loop++){
		fscanf(STDIN, "%d %d", $n, $c);
		$prices = fgets(STDIN);
		$prices = explode(' ', $prices);
		// echo "n = " . $n . " c = " . $c;

		$maxProfit = 0;

		for($i = 0; $i< $n; $i++){
			$profit = 0;
			$flag = true;
			$j = $i;
			while( $j < $n && $flag){
				if((int)$prices[$j] <= $c){
					$profit += $c - (int)$prices[$j];	
				}else{
					$flag = false;
				}	
				$j++;
			}
			if($profit > $maxProfit){
				$maxProfit = $profit;
			}
		}
		echo "max :: " .$maxProfit . "\n";
	}		
?>